In [1]:


import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('vendas_bruto.csv')

In [3]:
#Checar os tipos de dados de cada coluna
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 7 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           500 non-null    int64
 1   data_pedido        500 non-null    object
 2   cliente_nome       500 non-null    object
 3   cliente_email      493 non-null    object
 4   produto_categoria  500 non-null    object
 5   produto_preco      500 non-null    object
 6   quantidade         496 non-null    float64
dtypes: float64(1), int64(1), object(5)
memory usage: 27.5+ KB

In [5]:
#Convertendo as de String para data e ajustando os formatos
def converter_data(data_str):
  if pd.isna(data_str):
    return pd.NaT
  formato_datas = [
      '%Y-%m-%d',
      '%d/%m/%Y',
      '%Y-%b-%d',
      '%Y.%m.%d',
      '%d-%m-%Y',
      '%Y/%m/%d',
      '%d/%m/%Y',
      '%d-%m-%Y',
  ]

  for formato in formato_datas:
    try:
      return pd.to_datetime(data_str, format=formato)
    except:
      continue
  try:
        return pd.to_datetime(data_str, dayfirst=True, errors='coerce')
  except:
        return pd.NaT

In [6]:
df['data_ajustado'] = df['data_pedido'].apply(converter_data)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           500 non-null    int64
 1   data_pedido        500 non-null    object
 2   cliente_nome       500 non-null    object
 3   cliente_email      493 non-null    object
 4   produto_categoria  500 non-null    object
 5   produto_preco      500 non-null    object
 6   quantidade         496 non-null    float64
 7   data_ajustado      499 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 31.4+ KB

In [9]:
#Verificando o valor Nulo da data
df[df['data_ajustado'].isna()]

,id_venda,data_pedido,cliente_nome,cliente_email,produto_categoria,produto_preco,quantidade,data_ajustado
9,10,31/02/2024,Pedro Costa,pedro@email.com,Alimentos,"R$ 29,90",1.0,NaT

In [11]:
#Ajustando a data do Valor
df.loc[df['data_pedido'] == '31/02/2024', 'data_ajustado'] = '28/02/2024'

In [12]:
df['data_ajustado'].head()

0   2024-01-15
1   2024-02-15
2   2024-03-03
3   2024-01-20
4   2024-01-20
Name: data_ajustado, dtype: datetime64[ns]

In [13]:
#Verificando se existe algo inválido nos emails
print(df['cliente_email'].unique())

['joao@email.com' 'maria@email.com' nan 'ana@email.com'
 'roberto@email.com' 'fernanda@email.com' 'rafael@email.com'
 'carla@email.com' 'pedro@email.com' 'amanda@email.com' 'lucas@email.com'
 'juliana@email.com' 'bruno@email.com' 'patricia@email.com'
 'gustavo@email.com' 'vanessa@email.com' 'ricardo@email.com'
 'thiago@email.com' 'leticia@email.com' 'felipe@email.com'
 'camila@email.com' ',Eletrônicos,R$ 599' 'renata@email.com'
 'paulo@email.com' 'tatiana@email.com' 'andre@email.com' 'bruna@email.com'
 'cesar@email.com' 'daniela@email.com' 'fabio@email.com'
 'gabriela@email.com' 'heitor@email.com' 'igor@email.com'
 'jessica@email.com' 'karen@email.com' 'leonardo@email.com'
 'natalia@email.com' 'otavio@email.com' 'paula@email.com'
 'quintino@email.com' 'raquel@email.com' 'sabrina@email.com'
 'tomas@email.com' 'ursula@email.com' 'valter@email.com'
 'wilson@email.com' 'yara@email.com' 'zuleide@email.com'
 'adriana@email.com' 'bernardo@email.com' 'claudia@email.com'
 'david@email.com' 'eliane@email.com' 'fernando@email.com'
 'gisele@email.com' 'henrique@email.com' 'isabela@email.com'
 'jairo@email.com' 'katia@email.com' 'larissa@email.com'
 'marcelo@email.com' 'nadia@email.com' 'olga@email.com' 'queren@email.com'
 'rogerio@email.com' 'sonia@email.com' 'telma@email.com' 'ubi@email.com'
 'valeria@email.com' 'wagner@email.com' 'xuxa@email.com' 'yuri@email.com'
 'adilson@email.com' 'bianca@email.com' 'cristiano@email.com'
 'deborah@email.com' 'edson@email.com' 'fatima@email.com'
 'gloria@email.com' 'hugo@email.com' 'ivete@email.com' 'jo@email.com'
 'luciano@email.com' 'malu@email.com' 'neymar@email.com' 'oscar@email.com'
 'paolla@email.com' 'queiroz@email.com' 'silvio@email.com'
 'tarcisio@email.com' 'udo@email.com' 'vitor@email.com'
 'wanessa@email.com' 'xanddy@email.com' 'yonlu@email.com'
 'ziraldo@email.com' 'amir@email.com' 'bob@email.com' 'cazuza@email.com'
 'chico@email.com' 'dercy@email.com' 'elis@email.com' 'gilberto@email.com'
 'hebe@email.com' 'izabel@email.com' 'jair@email.com' 'klara@email.com'
 'lazaro@email.com' 'manoel@email.com' 'nelson@email.com'
 'quiteria@email.com' 'salvador@email.com' 'tati@email.com'
 'ubaldo@email.com' 'valentina@email.com' 'waldemar@email.com'
 'xenia@email.com' 'yolanda@email.com' 'zeramalho@email.com'
 'abelardo@email.com' 'beth@email.com' 'caca@email.com' 'dilma@email.com'
 'elba@email.com' 'garrincha@email.com' 'hildon@email.com'
 'ines@email.com' 'jorge@email.com' 'kaysar@email.com' 'lilia@email.com'
 'marcos@email.com' 'nina@email.com' 'pele@email.com'
 'quinzinho@email.com' 'ramses@email.com' 'suzana@email.com'
 'tufi@email.com' 'ubiratan@email.com' 'walt@email.com'
 'zacarias@email.com' 'aracy@email.com' 'danilo@email.com'
 'edna@email.com' 'floriano@email.com' 'gabriel@email.com'
 'hortencia@email.com' 'isadora@email.com' 'jackson@email.com'
 'kleber@email.com' 'lea@email.com' 'mario@email.com' 'nicole@email.com'
 'orlando@email.com' 'quico@email.com' 'renato@email.com'
 'sergio@email.com' 'tonia@email.com' 'valesca@email.com' 'yeda@email.com'
 'zeca@email.com' 'alcione@email.com' 'belchior@email.com'
 'cassia@email.com' 'dado@email.com' 'emicida@email.com' 'fafa@email.com'
 'gil@email.com' 'inacio@email.com' 'karina@email.com' 'luciana@email.com'
 'marilia@email.com' 'nando@email.com' 'oswaldo@email.com'
 'quercia@email.com' 'sandra@email.com' 'waldick@email.com'
 'xico@email.com' 'zilda@email.com' 'adriane@email.com'
 'arnaldo@email.com' 'carlinhos@email.com' 'eduardo@email.com'
 'geraldo@email.com' 'helio@email.com' 'isabel@email.com'
 'kelly@email.com' 'leandro@email.com' 'maisa@email.com' 'nivea@email.com'
 'quentin@email.com' 'ramon@email.com' 'selton@email.com'
 'teresa@email.com' 'ulysses@email.com' 'violeta@email.com'
 'wesley@email.com' ' Alimentos' 'yasmin@email.com' 'ze@email.com'
 'anitta@email.com' 'boni@email.com' 'cacau@email.com' 'dira@email.com'
 'emilio@email.com' 'humberto@email.com' 'irene@email.com'
 'olivia@email.com' 'quezia@email.com' 'taina@email.com'
 'valdineia@email.com' 'wanderlea@email.com' 'xande@email.com'
 'yvonne@email.com' 'zeze@email.com' 'alexandre@email.com'
 'antonio@email.com' 'barbara@email.com' 'caio@email.com'
 'danton@email.com' 'eriberto@email.com' 'george@email.com'
 'helena@email.com' 'isis@email.com' 'jayme@email.com' 'karine@email.com'
 'nanda@email.com' 'othon@email.com' 'rafaela@email.com'
 'samantha@email.com' 'vera@email.com' 'zecarlos@email.com'
 'beto@email.com' 'cid@email.com' 'diogo@email.com' 'elza@email.com'
 'kiko@email.com' 'leo@email.com' 'milton@email.com' 'otto@email.com'
 'quelynah@email.com' 'sandy@email.com' 'toni@email.com'
 'ulisses@email.com' 'victor@email.com' 'das@email.com' 'zelia@email.com'
 'baby@email.com' 'djavan@email.com' 'elisangela@email.com'
 'fafy@email.com' 'gretchen@email.com' 'luisa@email.com'
 'naiara@email.com' 'tania@email.com' 'val@email.com' 'waleska@email.com'
 'yan@email.com' 'angelica@email.com' 'daniel@email.com' 'fiuk@email.com'
 'heloisa@email.com' 'icaro@email.com' 'karla@email.com'
 'mariana@email.com' 'nicolas@email.com' 'samara@email.com'
 'tiago@email.com' 'uk@email.com' 'vitao@email.com'
 'whindersson@email.com' 'xuller@email.com' 'yudi@email.com'
 'zico@email.com' 'amado@email.com' 'cassio@email.com' 'debora@email.com'
 'gianecchini@email.com' 'hilda@email.com' 'karlos@email.com'
 'monica@email.com' 'otaviano@email.com' 'sophia@email.com'
 'tadeu@email.com' 'vitorino@email.com' 'walderez@email.com'
 'yona@email.com' 'zanoni@email.com' 'arlete@email.com' 'chay@email.com'
 'fulvio@email.com' 'guilherme@email.com' 'italo@email.com'
 'joaquim@email.com' 'kevinho@email.com' 'osmar@email.com'
 'quim@email.com' 'rayanne@email.com' 'simone@email.com' 'tato@email.com'
 'alinne@email.com' 'carlos@email.com' 'eddie@email.com' 'gigi@email.com'
 'helo@email.com' 'keyla@email.com' 'luigi@email.com' 'maite@email.com'
 'otoniel@email.com' 'ubiraci@email.com' 'valquiria@email.com'
 'xuxu@email.com' 'yami@email.com' 'zumira@email.com' 'berta@email.com'
 'edu@email.com' ' fatima@email.com' 'gilmelandia@email.com'
 'henri@email.com' 'isabella@email.com' 'jairzinho@email.com'
 'ubaldino@email.com' 'waltinho@email.com' 'xepa@email.com'
 'yohanna@email.com' 'zuleika@email.com' 'bernadete@email.com'
 'elenco@email.com' 'gilvan@email.com' 'helder@email.com' 'ivan@email.com'
 'jamile@email.com' 'leila@email.com' 'marcela@email.com'
 'natan@email.com' 'odilon@email.com' 'priscila@email.com'
 'raul@email.com' 'silmara@email.com' 'virginia@email.com'
 'washington@email.com' ',Roupas,R$ 449' 'alex@email.com']

In [14]:
#Checando o possível erro de email
df.loc[df['cliente_email'] == ',Eletrônicos,R$ 599']

,id_venda,data_pedido,cliente_nome,cliente_email,produto_categoria,produto_preco,quantidade,data_ajustado
23,24,2024/08/01,Diego Martins,",Eletrônicos,R$ 599","90""",1,NaN,2024-08-01

In [15]:
#Ajustando todos os dados do Cliente para depois ajustar os emails
df.loc[df['cliente_nome']=='Diego Martins', 'produto_categoria'] = 'Eletrônicos'
df.loc[df['cliente_nome']=='Diego Martins', 'produto_preco'] = 599
df.loc[df['cliente_nome']=='Diego Martins', 'quantidade'] = 1

In [16]:
df.loc[df['cliente_nome'] == 'Diego Martins']

,id_venda,data_pedido,cliente_nome,cliente_email,produto_categoria,produto_preco,quantidade,data_ajustado
23,24,2024/08/01,Diego Martins,",Eletrônicos,R$ 599",Eletrônicos,599,1.0,2024-08-01

In [17]:
df.loc[df['cliente_email'] == ',Roupas,R$ 449']

,id_venda,data_pedido,cliente_nome,cliente_email,produto_categoria,produto_preco,quantidade,data_ajustado
494,495,2024-10-04,Xênia,",Roupas,R$ 449","90""",1,NaN,2024-10-04

In [18]:
df.loc[df['cliente_email'] == ',Roupas,R$ 449', 'produto_categoria'] = 'Roupas'
df.loc[df['cliente_email'] == ',Roupas,R$ 449', 'produto_preco'] = 499
df.loc[df['cliente_email'] == ',Roupas,R$ 449', 'quantidade'] = 1

In [19]:
df.loc[df['cliente_nome'] == 'Xênia']

,id_venda,data_pedido,cliente_nome,cliente_email,produto_categoria,produto_preco,quantidade,data_ajustado
233,234,2024-Jun-28,Xênia,Alimentos,"R$ 49,90",-1,NaN,2024-06-28
494,495,2024-10-04,Xênia,",Roupas,R$ 449",Roupas,499,1.0,2024-10-04

In [20]:
condicao_xenia = (df['cliente_nome'] == 'Xênia') & (df['cliente_email'] == ' Alimentos')
df.loc[condicao_xenia, 'produto_categoria'] = 'Alimentos'
df.loc[condicao_xenia, 'produto_preco'] = 49.90
df.loc[condicao_xenia, 'quantidade'] = 1

condicao_jose = (df['cliente_nome'] == 'Jôse') & (df['cliente_email'] == ' Alimentos')
df.loc[condicao_jose, 'produto_categoria'] = 'Alimentos'
df.loc[condicao_jose, 'produto_preco'] = 69.90
df.loc[condicao_jose, 'quantidade'] = 1

In [21]:
df.loc[df['cliente_email'] == ' Alimentos']

,id_venda,data_pedido,cliente_nome,cliente_email,produto_categoria,produto_preco,quantidade,data_ajustado
233,234,2024-Jun-28,Xênia,Alimentos,Alimentos,49.9,1.0,2024-06-28
377,378,2024-Jul-12,Jôse,Alimentos,Alimentos,69.9,1.0,2024-07-12

In [22]:
df.loc[~df['cliente_email'].str.contains('@', na=False), 'cliente_email'] = pd.NA

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           500 non-null    int64
 1   data_pedido        500 non-null    object
 2   cliente_nome       500 non-null    object
 3   cliente_email      489 non-null    object
 4   produto_categoria  500 non-null    object
 5   produto_preco      500 non-null    object
 6   quantidade         500 non-null    float64
 7   data_ajustado      500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(1), object(5)
memory usage: 31.4+ KB

In [25]:
#Verificando se existe algum valor errado na coluna antes de passar valores para float
df['produto_preco'].unique()

array(['R$ 1.299,90', 'R$ 89,90', 'R$ 2.499,00', '59.90', 'R$ 149,90',
       'R$ 299,90', 'R$ 199,90', 'R$ 899', 'R$ 49,90', 'R$ 29,90',
       'R$ 3.499,00', 'R$ 799,90', 'R$ 59,90', 'R$ 39,90', 'R$ 79,90',
       'R$ 1.999,00', 'R$ 399,90', 'R$ 249,90', 'R$ 129,90',
       'R$ 1.499,00', 599, 'R$ 99,90', 'R$ 179,90', 'R$ 2.199,00',
       'R$ 2.999,00', 'R$ 899,90', 'R$ 599,90', 'R$ 219,90', 'R$ 69,90',
       'R$ 3.999,00', 'R$ 169,90', 'R$ 1.199,00', 'R$ 139,90',
       'R$ 549,90', 'R$ 119,90', 'R$ 899,00', 'R$ 1.799,00', 'R$ 349,90',
       'R$ 159,90', 'R$ 699,90', 'R$ 279,90', 'R$ 499,90', 'R$ 2.899,00',
       'R$ 319,90', 'R$ 4.999,00', 'R$ 229,90', 'R$ 749,90',
       'R$ 1.299,00', 'R$ 3.199,00', 'R$ 449,90', 'R$ 329,90',
       'R$ 1.599,00', 'R$ 3.299,00', 'R$ 4.499,00', 'R$ 1.399,00',
       'R$ 1.899,00', 'R$ 649,90', 'R$ 379,90', 'R$ 3.599,00',
       'R$ 1.099,00', 'R$ 949,00', 'R$ 3.799,00', 49.9, 'R$ 189,90',
       'R$ 479,90', 'R$ 259,90', 'R$ 4.199,00', 'R$ 109,90',
       'R$ 2.799,00', 'R$ 799,00', 'R$ 999,00', 'R$ 849,00',
       'R$ 3.899,00', 'R$ 239,90', 69.9, 'R$ 419,90', 'R$ 359,90',
       'R$ 1.699,00', 499], dtype=object)

In [26]:
#Passando os valores de String para Float
df['preco_str'] = df['produto_preco'].astype(str)

df['preco_str'] = df['preco_str'].str.replace('R$', '')
df['preco_str'] = df['preco_str'].str.replace('.', '', regex=False)
df['preco_str'] = df['preco_str'].str.replace(',', '.')
df['preco_str'] = df['preco_str'].str.strip()


df['produto_preco'] = pd.to_numeric(df['preco_str'], errors='coerce')


df.drop('preco_str', axis=1, inplace=True)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_venda           500 non-null    int64
 1   data_pedido        500 non-null    object
 2   cliente_nome       500 non-null    object
 3   cliente_email      489 non-null    object
 4   produto_categoria  500 non-null    object
 5   produto_preco      500 non-null    float64
 6   quantidade         500 non-null    float64
 7   data_ajustado      500 non-null    datetime64[ns]
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 31.4+ KB

In [28]:
#Verificando se possui algum erro de digitação em quantidade
df['quantidade'].unique()

array([ 1.,  2., -1., -2.,  3., -3.,  4.])

In [29]:
#Ajustando as quantidades que estão negativas
df.loc[df['quantidade']<0 ,'quantidade'] = abs(df.loc[df['quantidade']<0,'quantidade'])

In [30]:
df['quantidade'].unique()

array([1., 2., 3., 4.])

In [31]:
df.head()

,id_venda,data_pedido,cliente_nome,cliente_email,produto_categoria,produto_preco,quantidade,data_ajustado
0,1,2024-01-15,João Silva,joao@email.com,Eletrônicos,1299.9,1.0,2024-01-15
1,2,15/02/2024,Maria Santos,maria@email.com,Roupas,89.9,2.0,2024-02-15
2,3,2024-Mar-03,Carlos Lima,<NA>,Eletrônicos,2499.0,1.0,2024-03-03
3,4,2024.01.20,Ana Paula,ana@email.com,Livros,5990.0,1.0,2024-01-20
4,5,20/01/2024,João Silva,joao@email.com,Casa,149.9,1.0,2024-01-20

In [32]:
df['produto_categoria'].unique()

array(['Eletrônicos', 'Roupas', 'Livros', 'Casa', 'Esportes', 'Beleza',
       'Alimentos', 'Moveis'], dtype=object)

In [33]:
#Adicionando Uma nova coluna util para futuro dashboard
df['preco_total'] = df['produto_preco'] * df['quantidade']

In [34]:
df.head()

,id_venda,data_pedido,cliente_nome,cliente_email,produto_categoria,produto_preco,quantidade,data_ajustado,preco_total
0,1,2024-01-15,João Silva,joao@email.com,Eletrônicos,1299.9,1.0,2024-01-15,1299.9
1,2,15/02/2024,Maria Santos,maria@email.com,Roupas,89.9,2.0,2024-02-15,179.8
2,3,2024-Mar-03,Carlos Lima,<NA>,Eletrônicos,2499.0,1.0,2024-03-03,2499.0
3,4,2024.01.20,Ana Paula,ana@email.com,Livros,5990.0,1.0,2024-01-20,5990.0
4,5,20/01/2024,João Silva,joao@email.com,Casa,149.9,1.0,2024-01-20,149.9

In [35]:
#Alterando o . por , para não dar erro no Power BI
df['produto_preco'] = df['produto_preco'].apply(lambda x: f"{x:.2f}".replace('.', ','))

In [36]:
df['quantidade'] = df['quantidade'].apply(lambda x: f"{x:.2f}".replace('.', ','))
df['preco_total'] = df['preco_total'].apply(lambda x: f"{x:.2f}".replace('.', ','))
#Salvar arquivo limpo para dashboard
df.to_csv('dados_tratados.csv', index=False, encoding='utf-8-sig')